language: node_js
node_js:
  - "node"

git:
  depth: 2
  quiet: true

branches:
  only:
    - master
    - testing

script:
  - npm install
  - npm test

notifications:
  email:
    recipients:
      - oyarar84@gmail.com
    on_success: always
    on_failure: always
