language: node_js
node_js:
  - "node"

git:
  depth: 2
  quiet: true

#Github branches to test:

# blocklist
# branches:
#   except:
#   - legacy

# safelist
branches:
  only:
    - master

script:
  - npm install
  - npm test

notifications:
  email:
    recipients:
      - oyarar84@gmail.com
    on_success: always
    on_failure: always
